/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * version inject script
 * inject version from package.json to src/version.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');

// read package.json
const packageJsonPath = path.join(projectRoot, 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version;

// generate version.ts
const versionTsPath = path.join(projectRoot, 'src', 'version.ts');
const versionTsContent = `/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * version
 * this file is generated by build script, do not modify manually
 */
export const VERSION = '${version}';
`;

fs.writeFileSync(versionTsPath, versionTsContent, 'utf-8');

console.log(`✅ version: ${version}`);
