/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * version
 * this file is generated by build script, do not modify manually
 */
export const VERSION = '0.8.7';
